// This file is auto-generated by @hey-api/openapi-ts

export type DonatePayAuthBodyDto = {
    /**
     * Access token received from DonatePay OAuth flow
     */
    accessToken: string;
};

export type DonatePayAuthResponseDto = {
    /**
     * Indicates whether this authorization resulted in a new user registration
     */
    isNew: boolean;
};

export type IhaqAuthDto = {
    /**
     * OAuth authorization code received from IHAQ
     */
    code: string;
    /**
     * Redirect URI used in the OAuth flow
     */
    redirect_uri: string;
};

export type IhaqAuthResponseDto = {
    /**
     * Indicates whether this authorization resulted in a new user registration
     */
    isNew: boolean;
};

export type DonateHelperAuthBodyDto = {
    /**
     * API key from Donate Helper service
     */
    accessToken: string;
};

export type DonateHelperAuthResponseDto = {
    /**
     * Indicates whether this authorization resulted in a new user registration
     */
    isNew: boolean;
};

export type ExistingActiveTicketResponseDto = {
    /**
     * Random.org ticket ID
     */
    ticketId: string;
    /**
     * Timestamp when ticket was created
     */
    createdAt: string;
    /**
     * Remaining quota for today (out of 6)
     */
    quotaLeft: number;
};

export type NoActiveTicketResponseDto = {
    /**
     * Random.org ticket ID - null when no active ticket
     */
    ticketId: unknown;
    /**
     * Timestamp when ticket was created - null when no active ticket
     */
    createdAt: unknown;
    /**
     * Remaining quota for today (out of 6) - null when no active ticket
     */
    quotaLeft: unknown;
};

export type CreateTicketResponseDto = {
    /**
     * Random.org ticket ID
     */
    ticketId: string;
    /**
     * Timestamp when ticket was created
     */
    createdAt: string;
    /**
     * Remaining quota for today (out of 6)
     */
    quotaLeft: number;
};

export type ParticipantDto = {
    /**
     * Participant name
     */
    name?: string | null;
    /**
     * Bid amount for this participant
     */
    amount: number;
};

export type GenerateWinnerRequestDto = {
    /**
     * List of auction participants with their bid amounts
     */
    participants: Array<ParticipantDto>;
};

export type RandomOrgLicenseDto = {
    /**
     * License type
     */
    type: string;
    /**
     * License description text
     */
    text: string;
    /**
     * URL with more information about the license
     */
    infoUrl?: string | null;
};

export type RandomOrgTicketDataDto = {
    /**
     * Current ticket ID
     */
    ticketId: string;
    /**
     * Previous ticket ID in the chain
     */
    previousTicketId?: string | null;
    /**
     * Next ticket ID in the chain
     */
    nextTicketId?: string | null;
};

export type RandomOrgRandomDataDto = {
    /**
     * Random.org API method used
     */
    method: string;
    /**
     * Hashed API key for verification
     */
    hashedApiKey: string;
    /**
     * Number of random values generated
     */
    n: number;
    /**
     * Number of decimal places in the generated values
     */
    decimalPlaces: number;
    /**
     * Whether values are generated with replacement
     */
    replacement: boolean;
    /**
     * Pregenerated randomization data
     */
    pregeneratedRandomization?: {
        [key: string]: unknown;
    } | null;
    /**
     * Array of generated random decimal fractions
     */
    data: Array<number>;
    /**
     * License information for the random values
     */
    license: RandomOrgLicenseDto;
    /**
     * Additional license data
     */
    licenseData?: {
        [key: string]: unknown;
    } | null;
    /**
     * User-provided data returned with the response
     */
    userData?: {
        [key: string]: unknown;
    } | null;
    /**
     * Ticket data for verification chain
     */
    ticketData: RandomOrgTicketDataDto;
    /**
     * Timestamp when the random generation was completed
     */
    completionTime: string;
    /**
     * Serial number of the random generation
     */
    serialNumber: number;
};

export type GenerateWinnerResponseDto = {
    /**
     * Random data object from Random.org
     */
    random: RandomOrgRandomDataDto;
    /**
     * Digital signature from Random.org proving authenticity
     */
    signature: string;
    /**
     * Remaining quota for today (out of 6)
     */
    quotaLeft: number;
};

export type WinnerMetadataDto = {
    /**
     * Total amount from all participants
     */
    totalAmount: number;
    /**
     * Name of the selected winner
     */
    winnerName: string;
    /**
     * Number of lots (participants)
     */
    lotsCount: number;
};

export type WinnerRecordDto = {
    /**
     * Winner record ID
     */
    id: number;
    /**
     * User ID who generated this winner
     */
    userId: number;
    /**
     * Random.org ticket ID
     */
    ticketId: string;
    /**
     * Participants list as JSON array
     */
    participantsJson: Array<ParticipantDto>;
    /**
     * Random data object from Random.org
     */
    randomData: RandomOrgRandomDataDto;
    /**
     * Digital signature from Random.org
     */
    signature: string;
    /**
     * Metadata about the winner selection
     */
    metadata: WinnerMetadataDto;
    /**
     * Timestamp when winner was generated
     */
    createdAt: string;
};

export type RevealedTicketItemDto = {
    /**
     * Random.org ticket ID
     */
    ticketId: string;
    /**
     * Metadata about the winner selection
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Timestamp when winner was generated
     */
    createdAt: string;
};

export type RevealedTicketsResponseDto = {
    /**
     * List of revealed ticket records
     */
    items: Array<RevealedTicketItemDto>;
    /**
     * Total number of records available
     */
    total: number;
    /**
     * Current offset
     */
    offset: number;
    /**
     * Current limit
     */
    limit: number;
};

export type LotDto = {
    /**
     * Fast ID for quick lot identification
     */
    fastId: number;
    /**
     * Unique lot identifier
     */
    id: string;
    /**
     * Display name of the lot
     */
    name?: string | null;
    /**
     * Current bid amount in currency units
     */
    amount?: number | null;
};

export type LotsBroadcastDto = {
    /**
     * Array of lot data to be broadcasted
     */
    data: Array<LotDto>;
    /**
     * Timestamp of the lots broadcast in ISO format
     */
    timestamp?: string;
};

export type TimerDataDto = {
    /**
     * Current state of the timer
     */
    state: 'paused' | 'running';
    /**
     * Time remaining in milliseconds
     */
    timeLeft: number;
};

export type TimerBroadcastDto = {
    /**
     * Timer data to be broadcasted
     */
    data: TimerDataDto;
    /**
     * Timestamp of the timer broadcast in ISO format
     */
    timestamp?: string;
};

export type WheelParticipantDto = {
    /**
     * Name of the wheel participant
     */
    name: string;
    /**
     * Unique identifier for the participant
     */
    id: string;
    /**
     * Color assigned to the participant on the wheel (hex code)
     */
    color: string;
    /**
     * Bid amount or weight of the participant
     */
    amount: number;
    /**
     * Original amount of the participant. Used for the dropout wheel.
     */
    originalAmount: number | null;
};

export type WheelParticipantsChangedDto = {
    /**
     * Event type indicating participants have changed
     */
    type: 'participants-changed';
    /**
     * Array of current wheel participants
     */
    participants: Array<WheelParticipantDto>;
};

export type WheelSpinDto = {
    /**
     * Event type indicating a wheel spin
     */
    type: 'spin';
    /**
     * Final angle the wheel stopped at in degrees
     */
    angle: number;
    /**
     * Duration of the spin animation in milliseconds
     */
    duration: number;
    /**
     * Unique identifier of the winning participant
     */
    winner: string;
};

export type WheelSettingsChangedDto = {
    type: 'settings';
    /**
     * Type of the wheel format
     */
    format?: 0 | 1 | 2;
    /**
     * Core image of the wheel
     */
    coreImage?: string;
};

export type WheelBroadcastDto = {
    /**
     * Wheel event data (either participants changed or spin event)
     */
    data: WheelParticipantsChangedDto | WheelSpinDto | WheelSettingsChangedDto;
    /**
     * Timestamp of the wheel broadcast in ISO format
     */
    timestamp?: string;
};

export type RulesDataDto = {
    /**
     * Rules text content
     */
    text: string;
};

export type RulesBroadcastDto = {
    /**
     * Rules data to be broadcasted
     */
    data: RulesDataDto;
    /**
     * Timestamp of the rules broadcast in ISO format
     */
    timestamp?: string;
};

export type TokenResponseDto = {
    token: string;
    tokenId: string;
    role: string;
    permissions: Array<string>;
    expiresAt: string;
    createdAt: string;
};

export type RefreshTokenDto = {
    expiresIn?: string;
};

export type RefreshTokenResponseDto = {
    token: string;
    tokenId: string;
    role: string;
    permissions: Array<string>;
    expiresAt: string;
    createdAt: string;
    previousTokenRevoked: string;
};

export type RevokeTokenResponseDto = {
    message: string;
    role: string;
    revokedAt: string;
};

export type CreateCustomTokenDto = {
    permissions: Array<string>;
    description?: string;
    expiresIn?: string;
};

export type CustomTokenResponseDto = {
    token: string;
    tokenId: string;
    permissions: Array<string>;
    description?: string;
    expiresAt: string;
    createdAt: string;
    isRoleToken: boolean;
};

export type CustomTokenDto = {
    tokenId: string;
    permissions: Array<string>;
    description?: string;
    expiresAt: string;
    createdAt: string;
};

export type ListTokensResponseDto = {
    roleTokens?: {
        [key: string]: unknown;
    };
    customTokens?: Array<CustomTokenDto>;
};

export type RevokeCustomTokenResponseDto = {
    message: string;
    tokenId: string;
    revokedAt: string;
};

export type RevokeAllCustomTokensResponseDto = {
    message: string;
    revokedCount: number;
    revokedAt: string;
};

export type TokenInfoResponseDto = {
    tokenId: string;
    userId: number;
    permissions: Array<string>;
    role?: string;
    isRoleToken: boolean;
    expiresAt: string;
    createdAt: string;
    description?: string;
    isActive: boolean;
};

export type CanvasResolutionDto = {
    /**
     * Canvas width in pixels
     */
    width: number;
    /**
     * Canvas height in pixels
     */
    height: number;
};

export type TransformOriginDto = {
    /**
     * X coordinate
     */
    X: number;
    /**
     * Y coordinate
     */
    Y: number;
};

export type TransformSizeDto = {
    /**
     * Transform width
     */
    width: number;
    /**
     * Transform height
     */
    height: number;
};

export type TransformDto = {
    /**
     * Transform origin coordinates
     */
    origin: TransformOriginDto;
    /**
     * Transform size
     */
    size: TransformSizeDto;
};

export type AuctionOverlaySettingsDto = {
    showRules: boolean;
    showTable: boolean;
    showTimer: boolean;
    backgroundTransparency: number;
    autoscroll: boolean;
    autoscrollSpeed: number;
};

export type AuctionOverlayDto = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    /**
     * Canvas resolution in pixels
     */
    canvasResolution: CanvasResolutionDto;
    /**
     * Overlay transform settings
     */
    transform?: TransformDto | null;
    type: 'Auction' | 'Wheel';
    settings: AuctionOverlaySettingsDto;
};

export type WheelOverlaySettingsDto = {
    showWheel: boolean;
    showParticipants: boolean;
    backgroundTransparency: number;
};

export type WheelOverlayDto = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    /**
     * Canvas resolution in pixels
     */
    canvasResolution: CanvasResolutionDto;
    /**
     * Overlay transform settings
     */
    transform?: TransformDto | null;
    type: 'Auction' | 'Wheel';
    settings: WheelOverlaySettingsDto;
};

export type CreateAuctionOverlayDto = {
    name: string;
    type: 'Auction' | 'Wheel';
    settings: AuctionOverlaySettingsDto;
    /**
     * Canvas resolution in pixels
     */
    canvasResolution: CanvasResolutionDto;
    /**
     * Overlay transform settings
     */
    transform?: TransformDto | null;
};

export type CreateWheelOverlayDto = {
    name: string;
    type: 'Auction' | 'Wheel';
    settings: WheelOverlaySettingsDto;
    /**
     * Canvas resolution in pixels
     */
    canvasResolution: CanvasResolutionDto;
    /**
     * Overlay transform settings
     */
    transform?: TransformDto | null;
};

export type UpdateAuctionOverlayDto = {
    name?: string;
    settings?: AuctionOverlaySettingsDto;
    /**
     * Canvas resolution in pixels
     */
    canvasResolution?: CanvasResolutionDto;
    /**
     * Overlay transform settings
     */
    transform?: TransformDto | null;
};

export type UpdateWheelOverlayDto = {
    name?: string;
    settings?: WheelOverlaySettingsDto;
    /**
     * Canvas resolution in pixels
     */
    canvasResolution?: CanvasResolutionDto;
    /**
     * Overlay transform settings
     */
    transform?: TransformDto | null;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type UserControllerGetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type UserControllerGetUserResponses = {
    200: unknown;
};

export type UserControllerValidateIntegrationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/integration/validate';
};

export type UserControllerValidateIntegrationResponses = {
    200: unknown;
};

export type UserControllerSetAucSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/settings';
};

export type UserControllerSetAucSettingsResponses = {
    200: unknown;
};

export type DaControllerSubscribeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/da/centrifuge/subscribe';
};

export type DaControllerSubscribeResponses = {
    201: unknown;
};

export type DaControllerAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/da/auth';
};

export type DaControllerAuthorizeResponses = {
    201: unknown;
};

export type DaControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/da/revoke';
};

export type DaControllerRevokeResponses = {
    201: unknown;
};

export type TourniquetControllerAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourniquet/auth';
};

export type TourniquetControllerAuthorizeResponses = {
    201: unknown;
};

export type TourniquetControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourniquet/revoke';
};

export type TourniquetControllerRevokeResponses = {
    201: unknown;
};

export type TourniquetControllerWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourniquet/webhook';
};

export type TourniquetControllerWebhookResponses = {
    201: unknown;
};

export type TwitchControllerAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/twitch/auth';
};

export type TwitchControllerAuthorizeResponses = {
    201: unknown;
};

export type TwitchControllerDeleteRewardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/twitch/rewards';
};

export type TwitchControllerDeleteRewardsResponses = {
    200: unknown;
};

export type TwitchControllerUpdateRedemptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/twitch/redemptions';
};

export type TwitchControllerUpdateRedemptionResponses = {
    200: unknown;
};

export type TwitchControllerUpdateRedemptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/twitch/redemptions/batch';
};

export type TwitchControllerUpdateRedemptionsResponses = {
    200: unknown;
};

export type TwitchControllerUpdatePresetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/twitch/settings/presets';
};

export type TwitchControllerUpdatePresetsResponses = {
    200: unknown;
};

export type TwitchControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/twitch/revoke';
};

export type TwitchControllerRevokeResponses = {
    201: unknown;
};

export type DonatePayRuControllerAuthorizeData = {
    /**
     * DonatePay access token
     */
    body: DonatePayAuthBodyDto;
    path?: never;
    query?: never;
    url: '/donatePay/auth';
};

export type DonatePayRuControllerAuthorizeResponses = {
    /**
     * Successfully authorized with DonatePay
     */
    201: DonatePayAuthResponseDto;
};

export type DonatePayRuControllerAuthorizeResponse = DonatePayRuControllerAuthorizeResponses[keyof DonatePayRuControllerAuthorizeResponses];

export type DonatePayRuControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/donatePay/revoke';
};

export type DonatePayRuControllerRevokeResponses = {
    /**
     * Successfully revoked DonatePay integration
     */
    201: unknown;
};

export type DonatePayEuControllerAuthorizeData = {
    /**
     * DonatePay access token
     */
    body: DonatePayAuthBodyDto;
    path?: never;
    query?: never;
    url: '/donatePayEu/auth';
};

export type DonatePayEuControllerAuthorizeResponses = {
    /**
     * Successfully authorized with DonatePay
     */
    201: DonatePayAuthResponseDto;
};

export type DonatePayEuControllerAuthorizeResponse = DonatePayEuControllerAuthorizeResponses[keyof DonatePayEuControllerAuthorizeResponses];

export type DonatePayEuControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/donatePayEu/revoke';
};

export type DonatePayEuControllerRevokeResponses = {
    /**
     * Successfully revoked DonatePay integration
     */
    201: unknown;
};

export type IhaqControllerAuthorizeData = {
    /**
     * OAuth authorization code and redirect URI
     */
    body: IhaqAuthDto;
    path?: never;
    query?: never;
    url: '/ihaq/auth';
};

export type IhaqControllerAuthorizeResponses = {
    /**
     * Successfully authorized with IHAQ
     */
    201: IhaqAuthResponseDto;
};

export type IhaqControllerAuthorizeResponse = IhaqControllerAuthorizeResponses[keyof IhaqControllerAuthorizeResponses];

export type IhaqControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ihaq/revoke';
};

export type IhaqControllerRevokeResponses = {
    /**
     * Successfully revoked IHAQ integration
     */
    201: unknown;
};

export type DonateHelperControllerAuthorizeData = {
    /**
     * Donate Helper API key
     */
    body: DonateHelperAuthBodyDto;
    path?: never;
    query?: never;
    url: '/donateHelper/auth';
};

export type DonateHelperControllerAuthorizeResponses = {
    /**
     * Successfully authorized with Donate Helper
     */
    201: DonateHelperAuthResponseDto;
};

export type DonateHelperControllerAuthorizeResponse = DonateHelperControllerAuthorizeResponses[keyof DonateHelperControllerAuthorizeResponses];

export type DonateHelperControllerRevokeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/donateHelper/revoke';
};

export type DonateHelperControllerRevokeResponses = {
    /**
     * Successfully revoked Donate Helper integration
     */
    201: unknown;
};

export type RandomControllerGetRandomIntegerData = {
    body?: never;
    path?: never;
    query: {
        min: number;
        max: number;
    };
    url: '/random/integer';
};

export type RandomControllerGetRandomIntegerResponses = {
    200: unknown;
};

export type SignedRandomControllerCreateTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/random/signed/tickets';
};

export type SignedRandomControllerCreateTicketErrors = {
    /**
     * Active ticket already exists
     */
    400: {
        statusCode?: number;
        message?: string;
        code?: string;
    };
};

export type SignedRandomControllerCreateTicketError = SignedRandomControllerCreateTicketErrors[keyof SignedRandomControllerCreateTicketErrors];

export type SignedRandomControllerCreateTicketResponses = {
    /**
     * Ticket created successfully
     */
    201: CreateTicketResponseDto;
};

export type SignedRandomControllerCreateTicketResponse = SignedRandomControllerCreateTicketResponses[keyof SignedRandomControllerCreateTicketResponses];

export type SignedRandomControllerGetActiveTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/random/signed/tickets/active';
};

export type SignedRandomControllerGetActiveTicketResponses = {
    /**
     * Active ticket or empty response with null values
     */
    200: ExistingActiveTicketResponseDto | NoActiveTicketResponseDto;
};

export type SignedRandomControllerGetActiveTicketResponse = SignedRandomControllerGetActiveTicketResponses[keyof SignedRandomControllerGetActiveTicketResponses];

export type SignedRandomControllerGenerateWinnerData = {
    body: GenerateWinnerRequestDto;
    path?: never;
    query?: never;
    url: '/random/signed/winner';
};

export type SignedRandomControllerGenerateWinnerErrors = {
    /**
     * Daily quota exceeded
     */
    400: {
        statusCode?: number;
        message?: string;
        code?: string;
    };
    /**
     * Ticket has been used
     */
    422: {
        statusCode?: number;
        message?: string;
        code?: string;
    };
};

export type SignedRandomControllerGenerateWinnerError = SignedRandomControllerGenerateWinnerErrors[keyof SignedRandomControllerGenerateWinnerErrors];

export type SignedRandomControllerGenerateWinnerResponses = {
    /**
     * Winner generated successfully
     */
    201: GenerateWinnerResponseDto;
};

export type SignedRandomControllerGenerateWinnerResponse = SignedRandomControllerGenerateWinnerResponses[keyof SignedRandomControllerGenerateWinnerResponses];

export type SignedRandomControllerGetWinnerRecordByTicketData = {
    body?: never;
    path: {
        /**
         * Random.org ticket ID
         */
        ticketId: string;
    };
    query?: never;
    url: '/random/signed/records/ticket/{ticketId}';
};

export type SignedRandomControllerGetWinnerRecordByTicketErrors = {
    /**
     * Ticket is not revealed yet
     */
    400: {
        statusCode?: number;
        message?: string;
        code?: string;
    };
    /**
     * Winner record not found
     */
    404: unknown;
};

export type SignedRandomControllerGetWinnerRecordByTicketError = SignedRandomControllerGetWinnerRecordByTicketErrors[keyof SignedRandomControllerGetWinnerRecordByTicketErrors];

export type SignedRandomControllerGetWinnerRecordByTicketResponses = {
    /**
     * Winner record retrieved successfully
     */
    200: WinnerRecordDto;
};

export type SignedRandomControllerGetWinnerRecordByTicketResponse = SignedRandomControllerGetWinnerRecordByTicketResponses[keyof SignedRandomControllerGetWinnerRecordByTicketResponses];

export type SignedRandomControllerGetRevealedTicketsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User ID to fetch records for
         */
        userId: number;
        /**
         * Pagination offset
         */
        offset?: number;
        /**
         * Maximum records per page (max 20)
         */
        limit?: number;
    };
    url: '/random/signed/records/revealed';
};

export type SignedRandomControllerGetRevealedTicketsResponses = {
    /**
     * Revealed tickets retrieved successfully
     */
    200: RevealedTicketsResponseDto;
};

export type SignedRandomControllerGetRevealedTicketsResponse = SignedRandomControllerGetRevealedTicketsResponses[keyof SignedRandomControllerGetRevealedTicketsResponses];

export type BroadcastingControllerBroadcastLotsData = {
    body: LotsBroadcastDto;
    path?: never;
    query?: never;
    url: '/api/broadcast/lots';
};

export type BroadcastingControllerBroadcastLotsResponses = {
    201: unknown;
};

export type BroadcastingControllerBroadcastTimerData = {
    body: TimerBroadcastDto;
    path?: never;
    query?: never;
    url: '/api/broadcast/timer';
};

export type BroadcastingControllerBroadcastTimerResponses = {
    201: unknown;
};

export type BroadcastingControllerBroadcastWheelData = {
    body: WheelBroadcastDto;
    path?: never;
    query?: never;
    url: '/api/broadcast/wheel';
};

export type BroadcastingControllerBroadcastWheelResponses = {
    201: unknown;
};

export type BroadcastingControllerBroadcastRulesData = {
    body: RulesBroadcastDto;
    path?: never;
    query?: never;
    url: '/api/broadcast/rules';
};

export type BroadcastingControllerBroadcastRulesResponses = {
    201: unknown;
};

export type AuthControllerRevokeRoleTokenData = {
    body?: never;
    path: {
        role: 'api' | 'overlay' | 'viewer';
    };
    query?: never;
    url: '/auth/tokens/role/{role}';
};

export type AuthControllerRevokeRoleTokenResponses = {
    200: RevokeTokenResponseDto;
};

export type AuthControllerRevokeRoleTokenResponse = AuthControllerRevokeRoleTokenResponses[keyof AuthControllerRevokeRoleTokenResponses];

export type AuthControllerGetRoleTokenData = {
    body?: never;
    path: {
        role: 'api' | 'overlay' | 'viewer';
    };
    query?: never;
    url: '/auth/tokens/role/{role}';
};

export type AuthControllerGetRoleTokenResponses = {
    200: TokenResponseDto;
};

export type AuthControllerGetRoleTokenResponse = AuthControllerGetRoleTokenResponses[keyof AuthControllerGetRoleTokenResponses];

export type AuthControllerRefreshRoleTokenData = {
    body: RefreshTokenDto;
    path: {
        role: 'api' | 'overlay' | 'viewer';
    };
    query?: never;
    url: '/auth/tokens/role/{role}/refresh';
};

export type AuthControllerRefreshRoleTokenResponses = {
    200: RefreshTokenResponseDto;
};

export type AuthControllerRefreshRoleTokenResponse = AuthControllerRefreshRoleTokenResponses[keyof AuthControllerRefreshRoleTokenResponses];

export type AuthControllerRevokeAllCustomTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/tokens/custom';
};

export type AuthControllerRevokeAllCustomTokensResponses = {
    200: RevokeAllCustomTokensResponseDto;
};

export type AuthControllerRevokeAllCustomTokensResponse = AuthControllerRevokeAllCustomTokensResponses[keyof AuthControllerRevokeAllCustomTokensResponses];

export type AuthControllerCreateCustomTokenData = {
    body: CreateCustomTokenDto;
    path?: never;
    query?: never;
    url: '/auth/tokens/custom';
};

export type AuthControllerCreateCustomTokenResponses = {
    201: CustomTokenResponseDto;
};

export type AuthControllerCreateCustomTokenResponse = AuthControllerCreateCustomTokenResponses[keyof AuthControllerCreateCustomTokenResponses];

export type AuthControllerListTokensData = {
    body?: never;
    path?: never;
    query?: {
        type?: 'role' | 'custom' | 'all';
    };
    url: '/auth/tokens';
};

export type AuthControllerListTokensResponses = {
    200: ListTokensResponseDto;
};

export type AuthControllerListTokensResponse = AuthControllerListTokensResponses[keyof AuthControllerListTokensResponses];

export type AuthControllerRevokeCustomTokenData = {
    body?: never;
    path: {
        tokenId: string;
    };
    query?: never;
    url: '/auth/tokens/custom/{tokenId}';
};

export type AuthControllerRevokeCustomTokenResponses = {
    200: RevokeCustomTokenResponseDto;
};

export type AuthControllerRevokeCustomTokenResponse = AuthControllerRevokeCustomTokenResponses[keyof AuthControllerRevokeCustomTokenResponses];

export type AuthControllerGetTokenInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/tokens/info';
};

export type AuthControllerGetTokenInfoResponses = {
    200: TokenInfoResponseDto;
};

export type AuthControllerGetTokenInfoResponse = AuthControllerGetTokenInfoResponses[keyof AuthControllerGetTokenInfoResponses];

export type OverlaysControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/overlays';
};

export type OverlaysControllerListResponses = {
    200: Array<AuctionOverlayDto | WheelOverlayDto>;
};

export type OverlaysControllerListResponse = OverlaysControllerListResponses[keyof OverlaysControllerListResponses];

export type OverlaysControllerCreateData = {
    body: CreateAuctionOverlayDto | CreateWheelOverlayDto;
    path?: never;
    query?: never;
    url: '/overlays';
};

export type OverlaysControllerCreateResponses = {
    201: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerCreateResponse = OverlaysControllerCreateResponses[keyof OverlaysControllerCreateResponses];

export type OverlaysControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/overlays/{id}';
};

export type OverlaysControllerRemoveResponses = {
    204: void;
};

export type OverlaysControllerRemoveResponse = OverlaysControllerRemoveResponses[keyof OverlaysControllerRemoveResponses];

export type OverlaysControllerGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/overlays/{id}';
};

export type OverlaysControllerGetResponses = {
    200: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerGetResponse = OverlaysControllerGetResponses[keyof OverlaysControllerGetResponses];

export type OverlaysControllerUpdateData = {
    body: UpdateAuctionOverlayDto | UpdateWheelOverlayDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/overlays/{id}';
};

export type OverlaysControllerUpdateResponses = {
    200: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerUpdateResponse = OverlaysControllerUpdateResponses[keyof OverlaysControllerUpdateResponses];

export type OverlaysControllerReplaceData = {
    body: CreateAuctionOverlayDto | CreateWheelOverlayDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/overlays/{id}';
};

export type OverlaysControllerReplaceResponses = {
    200: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerReplaceResponse = OverlaysControllerReplaceResponses[keyof OverlaysControllerReplaceResponses];

export type ClientOptions = {
    baseURL: string;
};