// This file is auto-generated by @hey-api/openapi-ts

export type LotDto = {
  /**
   * Fast ID for quick lot identification
   */
  fastId: number;
  /**
   * Unique lot identifier
   */
  id: string;
  /**
   * Display name of the lot
   */
  name?: string | null;
  /**
   * Current bid amount in currency units
   */
  amount?: number | null;
};

export type LotsBroadcastDto = {
  /**
   * Array of lot data to be broadcasted
   */
  data: Array<LotDto>;
  /**
   * Timestamp of the lots broadcast in ISO format
   */
  timestamp?: string;
};

export type TimerDataDto = {
  /**
   * Current state of the timer
   */
  state: 'paused' | 'running';
  /**
   * Time remaining in milliseconds
   */
  timeLeft: number;
};

export type TimerBroadcastDto = {
  /**
   * Timer data to be broadcasted
   */
  data: TimerDataDto;
  /**
   * Timestamp of the timer broadcast in ISO format
   */
  timestamp?: string;
};

export type WheelParticipantDto = {
  /**
   * Name of the wheel participant
   */
  name: string;
  /**
   * Unique identifier for the participant
   */
  id: string;
  /**
   * Color assigned to the participant on the wheel (hex code)
   */
  color: string;
  /**
   * Bid amount or weight of the participant
   */
  amount: number;
};

export type WheelParticipantsChangedDto = {
  /**
   * Event type indicating participants have changed
   */
  type: 'participants-changed';
  /**
   * Array of current wheel participants
   */
  participants: Array<WheelParticipantDto>;
};

export type WheelSpinDto = {
  /**
   * Event type indicating a wheel spin
   */
  type: 'spin';
  /**
   * Final angle the wheel stopped at in degrees
   */
  angle: number;
  /**
   * Duration of the spin animation in milliseconds
   */
  duration: number;
  /**
   * Unique identifier of the winning participant
   */
  winner: string;
};

export type WheelBroadcastDto = {
  /**
   * Wheel event data (either participants changed or spin event)
   */
  data: WheelParticipantsChangedDto | WheelSpinDto;
  /**
   * Timestamp of the wheel broadcast in ISO format
   */
  timestamp?: string;
};

export type SettingsBroadcastDto = {
  /**
   * Settings data to be broadcasted (flexible structure)
   */
  data: {
    [key: string]: unknown;
  };
  /**
   * Timestamp of the settings broadcast in ISO format
   */
  timestamp?: string;
};

export type TokenResponseDto = {
  token: string;
  tokenId: string;
  role: string;
  permissions: Array<string>;
  expiresAt: string;
  createdAt: string;
};

export type RefreshTokenDto = {
  expiresIn?: string;
};

export type RefreshTokenResponseDto = {
  token: string;
  tokenId: string;
  role: string;
  permissions: Array<string>;
  expiresAt: string;
  createdAt: string;
  previousTokenRevoked: string;
};

export type RevokeTokenResponseDto = {
  message: string;
  role: string;
  revokedAt: string;
};

export type CreateCustomTokenDto = {
  permissions: Array<string>;
  description?: string;
  expiresIn?: string;
};

export type CustomTokenResponseDto = {
  token: string;
  tokenId: string;
  permissions: Array<string>;
  description?: string;
  expiresAt: string;
  createdAt: string;
  isRoleToken: boolean;
};

export type CustomTokenDto = {
  tokenId: string;
  permissions: Array<string>;
  description?: string;
  expiresAt: string;
  createdAt: string;
};

export type ListTokensResponseDto = {
  roleTokens?: {
    [key: string]: unknown;
  };
  customTokens?: Array<CustomTokenDto>;
};

export type RevokeCustomTokenResponseDto = {
  message: string;
  tokenId: string;
  revokedAt: string;
};

export type RevokeAllCustomTokensResponseDto = {
  message: string;
  revokedCount: number;
  revokedAt: string;
};

export type TokenInfoResponseDto = {
  tokenId: string;
  userId: number;
  permissions: Array<string>;
  role?: string;
  isRoleToken: boolean;
  expiresAt: string;
  createdAt: string;
  description?: string;
  isActive: boolean;
};

export type AuctionOverlaySettingsDto = {
  showRules: boolean;
  showTable: boolean;
  showTimer: boolean;
  backgroundTransparency: number;
  autoscroll: boolean;
  autoscrollSpeed: number;
};

export type AuctionOverlayDto = {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  type: 'Auction' | 'Wheel';
  settings: AuctionOverlaySettingsDto;
};

export type WheelOverlaySettingsDto = {
  showWheel: boolean;
  showParticipants: boolean;
  backgroundTransparency: number;
};

export type WheelOverlayDto = {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  type: 'Auction' | 'Wheel';
  settings: WheelOverlaySettingsDto;
};

export type CreateAuctionOverlayDto = {
  name: string;
  type: 'Auction' | 'Wheel';
  settings: AuctionOverlaySettingsDto;
};

export type CreateWheelOverlayDto = {
  name: string;
  type: 'Auction' | 'Wheel';
  settings: WheelOverlaySettingsDto;
};

export type UpdateAuctionOverlayDto = {
  name?: string;
  settings?: AuctionOverlaySettingsDto;
};

export type UpdateWheelOverlayDto = {
  name?: string;
  settings?: WheelOverlaySettingsDto;
};

export type AppControllerGetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/app';
};

export type AppControllerGetHelloResponses = {
  200: unknown;
};

export type UserControllerGetUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user';
};

export type UserControllerGetUserResponses = {
  200: unknown;
};

export type UserControllerValidateIntegrationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/integration/validate';
};

export type UserControllerValidateIntegrationResponses = {
  200: unknown;
};

export type UserControllerSetAucSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/settings';
};

export type UserControllerSetAucSettingsResponses = {
  200: unknown;
};

export type DaControllerSubscribeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/da/centrifuge/subscribe';
};

export type DaControllerSubscribeResponses = {
  201: unknown;
};

export type DaControllerAuthorizeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/da/auth';
};

export type DaControllerAuthorizeResponses = {
  201: unknown;
};

export type DaControllerRevokeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/da/revoke';
};

export type DaControllerRevokeResponses = {
  201: unknown;
};

export type TourniquetControllerAuthorizeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tourniquet/auth';
};

export type TourniquetControllerAuthorizeResponses = {
  201: unknown;
};

export type TourniquetControllerRevokeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tourniquet/revoke';
};

export type TourniquetControllerRevokeResponses = {
  201: unknown;
};

export type TourniquetControllerWebhookData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tourniquet/webhook';
};

export type TourniquetControllerWebhookResponses = {
  201: unknown;
};

export type TwitchControllerAuthorizeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/auth';
};

export type TwitchControllerAuthorizeResponses = {
  201: unknown;
};

export type TwitchControllerDeleteRewardsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/rewards';
};

export type TwitchControllerDeleteRewardsResponses = {
  200: unknown;
};

export type TwitchControllerUpdateRedemptionData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/redemptions';
};

export type TwitchControllerUpdateRedemptionResponses = {
  200: unknown;
};

export type TwitchControllerUpdateRedemptionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/redemptions/batch';
};

export type TwitchControllerUpdateRedemptionsResponses = {
  200: unknown;
};

export type TwitchControllerUpdatePresetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/settings/presets';
};

export type TwitchControllerUpdatePresetsResponses = {
  200: unknown;
};

export type TwitchControllerRevokeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/revoke';
};

export type TwitchControllerRevokeResponses = {
  201: unknown;
};

export type TwitchWebhookControllerNotificationData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/twitch/webhook/notification';
};

export type TwitchWebhookControllerNotificationResponses = {
  200: unknown;
};

export type DonatePayControllerAuthorizeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/donatePay/auth';
};

export type DonatePayControllerAuthorizeResponses = {
  201: unknown;
};

export type DonatePayControllerRevokeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/donatePay/revoke';
};

export type DonatePayControllerRevokeResponses = {
  201: unknown;
};

export type RandomControllerGetRandomIntegerData = {
  body?: never;
  path?: never;
  query: {
    min: number;
    max: number;
  };
  url: '/random/integer';
};

export type RandomControllerGetRandomIntegerResponses = {
  200: unknown;
};

export type BroadcastingControllerBroadcastLotsData = {
  body: LotsBroadcastDto;
  path?: never;
  query?: never;
  url: '/api/broadcast/lots';
};

export type BroadcastingControllerBroadcastLotsResponses = {
  201: unknown;
};

export type BroadcastingControllerBroadcastTimerData = {
  body: TimerBroadcastDto;
  path?: never;
  query?: never;
  url: '/api/broadcast/timer';
};

export type BroadcastingControllerBroadcastTimerResponses = {
  201: unknown;
};

export type BroadcastingControllerBroadcastWheelData = {
  body: WheelBroadcastDto;
  path?: never;
  query?: never;
  url: '/api/broadcast/wheel';
};

export type BroadcastingControllerBroadcastWheelResponses = {
  201: unknown;
};

export type BroadcastingControllerBroadcastSettingsData = {
  body: SettingsBroadcastDto;
  path?: never;
  query?: never;
  url: '/api/broadcast/settings';
};

export type BroadcastingControllerBroadcastSettingsResponses = {
  201: unknown;
};

export type AuthControllerRevokeRoleTokenData = {
  body?: never;
  path: {
    role: 'api' | 'overlay' | 'viewer';
  };
  query?: never;
  url: '/auth/tokens/role/{role}';
};

export type AuthControllerRevokeRoleTokenResponses = {
  200: RevokeTokenResponseDto;
};

export type AuthControllerRevokeRoleTokenResponse =
  AuthControllerRevokeRoleTokenResponses[keyof AuthControllerRevokeRoleTokenResponses];

export type AuthControllerGetRoleTokenData = {
  body?: never;
  path: {
    role: 'api' | 'overlay' | 'viewer';
  };
  query?: never;
  url: '/auth/tokens/role/{role}';
};

export type AuthControllerGetRoleTokenResponses = {
  200: TokenResponseDto;
};

export type AuthControllerGetRoleTokenResponse =
  AuthControllerGetRoleTokenResponses[keyof AuthControllerGetRoleTokenResponses];

export type AuthControllerRefreshRoleTokenData = {
  body: RefreshTokenDto;
  path: {
    role: 'api' | 'overlay' | 'viewer';
  };
  query?: never;
  url: '/auth/tokens/role/{role}/refresh';
};

export type AuthControllerRefreshRoleTokenResponses = {
  200: RefreshTokenResponseDto;
};

export type AuthControllerRefreshRoleTokenResponse =
  AuthControllerRefreshRoleTokenResponses[keyof AuthControllerRefreshRoleTokenResponses];

export type AuthControllerRevokeAllCustomTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/tokens/custom';
};

export type AuthControllerRevokeAllCustomTokensResponses = {
  200: RevokeAllCustomTokensResponseDto;
};

export type AuthControllerRevokeAllCustomTokensResponse =
  AuthControllerRevokeAllCustomTokensResponses[keyof AuthControllerRevokeAllCustomTokensResponses];

export type AuthControllerCreateCustomTokenData = {
  body: CreateCustomTokenDto;
  path?: never;
  query?: never;
  url: '/auth/tokens/custom';
};

export type AuthControllerCreateCustomTokenResponses = {
  201: CustomTokenResponseDto;
};

export type AuthControllerCreateCustomTokenResponse =
  AuthControllerCreateCustomTokenResponses[keyof AuthControllerCreateCustomTokenResponses];

export type AuthControllerListTokensData = {
  body?: never;
  path?: never;
  query?: {
    type?: 'role' | 'custom' | 'all';
  };
  url: '/auth/tokens';
};

export type AuthControllerListTokensResponses = {
  200: ListTokensResponseDto;
};

export type AuthControllerListTokensResponse =
  AuthControllerListTokensResponses[keyof AuthControllerListTokensResponses];

export type AuthControllerRevokeCustomTokenData = {
  body?: never;
  path: {
    tokenId: string;
  };
  query?: never;
  url: '/auth/tokens/custom/{tokenId}';
};

export type AuthControllerRevokeCustomTokenResponses = {
  200: RevokeCustomTokenResponseDto;
};

export type AuthControllerRevokeCustomTokenResponse =
  AuthControllerRevokeCustomTokenResponses[keyof AuthControllerRevokeCustomTokenResponses];

export type AuthControllerGetTokenInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/tokens/info';
};

export type AuthControllerGetTokenInfoResponses = {
  200: TokenInfoResponseDto;
};

export type AuthControllerGetTokenInfoResponse =
  AuthControllerGetTokenInfoResponses[keyof AuthControllerGetTokenInfoResponses];

export type OverlaysControllerListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/overlays';
};

export type OverlaysControllerListResponses = {
  200: Array<AuctionOverlayDto | WheelOverlayDto>;
};

export type OverlaysControllerListResponse = OverlaysControllerListResponses[keyof OverlaysControllerListResponses];

export type OverlaysControllerCreateData = {
  body: CreateAuctionOverlayDto | CreateWheelOverlayDto;
  path?: never;
  query?: never;
  url: '/overlays';
};

export type OverlaysControllerCreateResponses = {
  201: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerCreateResponse =
  OverlaysControllerCreateResponses[keyof OverlaysControllerCreateResponses];

export type OverlaysControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/overlays/{id}';
};

export type OverlaysControllerRemoveResponses = {
  204: void;
};

export type OverlaysControllerRemoveResponse =
  OverlaysControllerRemoveResponses[keyof OverlaysControllerRemoveResponses];

export type OverlaysControllerGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/overlays/{id}';
};

export type OverlaysControllerGetResponses = {
  200: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerGetResponse = OverlaysControllerGetResponses[keyof OverlaysControllerGetResponses];

export type OverlaysControllerUpdateData = {
  body: UpdateAuctionOverlayDto | UpdateWheelOverlayDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/overlays/{id}';
};

export type OverlaysControllerUpdateResponses = {
  200: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerUpdateResponse =
  OverlaysControllerUpdateResponses[keyof OverlaysControllerUpdateResponses];

export type OverlaysControllerReplaceData = {
  body: CreateAuctionOverlayDto | CreateWheelOverlayDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/overlays/{id}';
};

export type OverlaysControllerReplaceResponses = {
  200: AuctionOverlayDto | WheelOverlayDto;
};

export type OverlaysControllerReplaceResponse =
  OverlaysControllerReplaceResponses[keyof OverlaysControllerReplaceResponses];

export type ClientOptions = {
  baseURL: string;
};
